### PR TITLE
Apple M1 builds

### LINKED ISSUE #502: Activating extension ban.spellright failed (MacOS M1)
I am on MacOS (M1) with the latest version of VS Code and SpellRight, when I start VS Code the extension fails to load with the following error. Any ideas?

```
[2022-04-18 16:07:03.179] [exthost] [error] Activating extension ban.spellright failed due to an error:

[2022-04-18 16:07:03.179] [exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (/Users/Kian.Kashani@teck.com/.vscode/extensions/ban.spellright-3.0.62/lib/bindings.js:46:25)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32156)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28749)
	at Function.g._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at Object.<anonymous> (/Users/Kian.Kashani@teck.com/.vscode/extensions/ban.spellright-3.0.62/src/spellright.js:18:18)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
	at Module.load (node:internal/modules/cjs/loader:1035:32)
	at Module._load (node:internal/modules/cjs/loader:876:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:32156)
	at Function.E._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:28749)
	at Function.g._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:61429)
	at Module.require (node:internal/modules/cjs/loader:1059:19)
	at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:699)
	at activate (/Users/Kian.Kashani@teck.com/.vscode/extensions/ban.spellright-3.0.62/src/extension.js:21:24)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:16070)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:15731)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:13549
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async g._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8154)
	at async g._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8096)
	at async g._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7460)
```

### PR DESCRIPTION
**Pull request by borekb**
This PR fixes a couple of scripts and regenerates arm64 (Apple Silicon, M1 chip) binaries.

Fixes #502

### CODE REVIEW

**Comment by borekb** [comment]
Commits above are my first attempts but the resulting files in b7fcb2b5b214996aa10824a0b81aa6672bdc30b5 don't seem to resolve issues reported in #502.

@bartosz-antosik, what version of Node.js and other global tools I should have? For example, I'm getting this error:

Screen Shot 2022-04-21 at 20 56 04

As text:

```console
$ ./build-macos-apple.sh
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.14.2 | darwin | x64
gyp info find Python using Python version 3.9.12 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/borekb/.nvs/node/16.14.2/x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/borekb/dev/temp/vscode-spellright/lib/bin/node-spellchecker/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/borekb/.nvs/node/16.14.2/x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/borekb/Library/Caches/node-gyp/13.1.7/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/borekb/Library/Caches/node-gyp/13.1.7',
gyp info spawn args   '-Dnode_gyp_dir=/Users/borekb/.nvs/node/16.14.2/x64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/borekb/Library/Caches/node-gyp/13.1.7/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/borekb/dev/temp/vscode-spellright/lib/bin/node-spellchecker',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/borekb/.nvs/node/16.14.2/x64/lib/node_modules/node-gyp/lib/configure.js:261:16)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/borekb/.nvs/node/16.14.2/x64/bin/node" "/Users/borekb/.nvs/default/bin/node-gyp" "rebuild" "--target=13.1.7" "--arch=x64" "--dist-url=https://atom.io/download/electron"
gyp ERR! cwd /Users/borekb/dev/temp/vscode-spellright/lib/bin/node-spellchecker
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok
cp: build/Release/spellchecker.node: No such file or directory
```

**Comment by borekb** [comment]
BTW, on macOS Monterey, Python 2 is no longer installed. This is a way to do it: https://www.alfredapp.com/help/kb/python-2-monterey/

In short:

```sh
brew install pyenv
pyenv install 2.7.18
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "${HOMEBREW_PREFIX}/bin/python"
```

**Comment by borekb** [comment]
a6a0e6e addresses the error mentioned above using a technique found [here](https://stackoverflow.com/a/71523704/21728).

The next commit are re-generated binaries but it still doesn't work in VSCode:

Screen Shot 2022-04-21 at 21 12 14

```
[exthost] [error] TypeError: Cannot read properties of null (reading 'Spellchecker')
```

I've updated the files in `~/.vscode/extensions/ban.spellright-3.0.62/lib/bin` and checked their permissions:

Screen Shot 2022-04-21 at 21 13 22

**Comment by bartosz-antosik** [comment]
@borekb Just an idea: Could you check `--arch=x64` switch in the script that builds the binaries? I am not sure about it (as about anything considering Mx chip).

**Comment by borekb** [comment]
@bartosz-antosik bcfbb00 and 🎉:

Screen Shot 2022-04-21 at 23 28 32

**Pull request merged**
